name: mosdef-binder

channels:
  - conda-forge

dependencies:
  - python=3.10
  - numpy
  - scipy
  - packmol>=1!18.013
  - nglview
  - py3dmol
  - oset
  - parmed
  - mdtraj
  - mbuild
  - foyer
  - gmso
  - gsd
  - openbabel>=3.0.0
  - jupyter
  - nbformat
  - ipykernel
  - openmm
  - networkx
  - six
  - plyplus
  - requests
  - lxml
